# Deploy to Azure App Service (Web App for Containers) Template
# Parameters: serviceConnection, appServiceName, acrName, imageName, imageTag, keyVaultName

parameters:
  - name: serviceConnection
    type: string
  - name: appServiceName
    type: string
  - name: acrName
    type: string
  - name: imageName
    type: string
  - name: imageTag
    type: string
  - name: keyVaultName
    type: string
    default: ''

jobs:
  - deployment: DeployAppService
    displayName: 'Deploy to App Service (Web App for Containers)'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureCLI@2
              displayName: 'Configure App Service Container Settings'
              inputs:
                azureSubscription: ${{ parameters.serviceConnection }}
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  # Set the container image for App Service
                  az webapp config container set \
                    --name ${{ parameters.appServiceName }} \
                    --resource-group $(RG_NAME) \
                    --docker-custom-image-name ${{ parameters.acrName }}.azurecr.io/${{ parameters.imageName }}:${{ parameters.imageTag }} \
                    --docker-registry-server-url https://${{ parameters.acrName }}.azurecr.io

            - task: AzureWebAppContainer@1
              displayName: 'Deploy Container to App Service'
              inputs:
                azureSubscription: ${{ parameters.serviceConnection }}
                appName: ${{ parameters.appServiceName }}
                containers: ${{ parameters.acrName }}.azurecr.io/${{ parameters.imageName }}:${{ parameters.imageTag }}

            # Optional: Configure App Settings from Key Vault
            - ${{ if ne(parameters.keyVaultName, '') }}:
              - task: AzureCLI@2
                displayName: 'Configure App Settings with Key Vault References'
                inputs:
                  azureSubscription: ${{ parameters.serviceConnection }}
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    echo "Setting Key Vault references in App Service app settings..."
                    # Example: Reference secrets from Key Vault
                    # az webapp config appsettings set \
                    #   --name ${{ parameters.appServiceName }} \
                    #   --resource-group $(RG_NAME) \
                    #   --settings \
                    #     "DATABASE_CONNECTION_STRING=@Microsoft.KeyVault(SecretUri=https://${{ parameters.keyVaultName }}.vault.azure.net/secrets/DatabaseConnectionString/)" \
                    #     "API_KEY=@Microsoft.KeyVault(SecretUri=https://${{ parameters.keyVaultName }}.vault.azure.net/secrets/ApiKey/)"
                    echo "Key Vault reference configuration completed"

            - task: AzureAppServiceManage@0
              displayName: 'Restart App Service'
              inputs:
                azureSubscription: ${{ parameters.serviceConnection }}
                Action: 'Restart Azure App Service'
                WebAppName: ${{ parameters.appServiceName }}

            - script: |
                echo "Application deployed successfully!"
                echo "URL: https://${{ parameters.appServiceName }}.azurewebsites.net"
              displayName: 'Deployment Summary'
